MRBooker/Controllers/PlaceController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MRBooker.Data.UoW;
using MRBooker.Data.Models.Entities;
using MRBooker.Wrappers;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace MRBooker.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PlaceController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public PlaceController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: Place
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewData["CurrentSort"] = sortOrder;

            ViewData["CountrySortParm"] = string.IsNullOrEmpty(sortOrder) ? "country_desc" : "";
            ViewData["RegionSortParm"] = string.IsNullOrEmpty(sortOrder) ? "region_desc" : "";
            ViewData["CitySortParm"] = string.IsNullOrEmpty(sortOrder) ? "city_desc" : "";
            ViewData["StreetSortParm"] = string.IsNullOrEmpty(sortOrder) ? "street_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var places = _unitOfWork.PlaceRepository.GetAll();

            if (!string.IsNullOrEmpty(searchString))
            {
                places = places.Where(r => r.City.ToLowerInvariant().Contains(searchString.ToLowerInvariant()) ||
                                    r.Country.ToLowerInvariant().Contains(searchString.ToLowerInvariant()) ||
                                    r.PostalCode.ToLowerInvariant().Contains(searchString.ToLowerInvariant()) || 
                                    r.Region.ToLowerInvariant().Contains(searchString.ToLowerInvariant()) || 
                                    r.StreetName.ToLowerInvariant().Contains(searchString.ToLowerInvariant()) ||
                                    r.StreetNumber.ToLowerInvariant().Contains(searchString.ToLowerInvariant()));
            }

            switch (sortOrder)
            {
                case "country_desc":
                    places = places.OrderByDescending(s => s.Country);
                    break;

                case "region_desc":
                    places = places.OrderByDescending(s => s.Region);
                    break;

                case "city_desc":
                    places = places.OrderByDescending(s => s.City);
                    break;

                case "street_desc":
                    places = places.OrderByDescending(s => s.StreetName);
                    break;

                case "Date":
                    places = places.OrderBy(s => s.AddedDate);
                    break;
                case "date_desc":
                    places = places.OrderByDescending(s => s.AddedDate);
                    break;
                default:
                    places = places.OrderBy(s => s.Country);
                    break;
            }

            int pageSize = 10;
            return View(await PaginatedList<Place>.CreateAsync(places.AsNoTracking(), page ?? 1, pageSize));
        }

        // GET: Place/Details/5
        public ActionResult Details(int id)
        {
            var place = _unitOfWork.PlaceRepository.GetAll().FirstOrDefault(x => x.Id == id);

            return View(place);
        }

        // GET: Place/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Place/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                var place = new Place();
                place.City = collection["City"];
                place.Country = collection["Country"];
                place.Floor = Convert.ToInt32(collection["Floor"]);
                place.PostalCode = collection["PostalCode"];
                place.Region = collection["Region"];
                place.StreetName = collection["StreetName"];
                place.StreetNumber = collection["StreetNumber"];
                place.AddedDate = DateTime.Now;
                place.ModifiedDate = DateTime.Now;
                place.IPAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString();

                _unitOfWork.PlaceRepository.Insert(place);
                _unitOfWork.Save();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: Place/Edit/5
        public ActionResult Edit(int id)
        {
            var place = _unitOfWork.PlaceRepository.GetAll().FirstOrDefault(x => x.Id == id);

            return View(place);
        }

        // POST: Place/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                var place = _unitOfWork.PlaceRepository.GetAll().FirstOrDefault(x => x.Id == id);
                place.City = collection["City"];
                place.Country = collection["Country"];
                place.Floor = Convert.ToInt32(collection["Floor"]);
                place.PostalCode = collection["PostalCode"];
                place.Region = collection["Region"];
                place.StreetName = collection["StreetName"];
                place.StreetNumber = collection["StreetNumber"];
                place.ModifiedDate = DateTime.Now;
                place.IPAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString();

                _unitOfWork.PlaceRepository.Update(place);
                _unitOfWork.Save();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // POST: Place/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                var place = _unitOfWork.PlaceRepository.GetAll().FirstOrDefault(x => x.Id == id);
                _unitOfWork.PlaceRepository.Delete(place);
                _unitOfWork.Save();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Error");
            }
        }
    }
}

MRBooker/Controllers/RoomController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MRBooker.Data.UoW;
using Microsoft.EntityFrameworkCore;
using MRBooker.Data.Models.Entities;
using Microsoft.AspNetCore.Authorization;
using MRBooker.Wrappers;
using MRBooker.Extensions.DtoMappers;
using MRBooker.Business.Models.Room;
using System.Collections.Generic;
using MRBooker.Business.Models.Place;

namespace MRBooker.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoomController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public RoomController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: Room
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var rooms = _unitOfWork.RoomRepository.GetAll();

            if (!string.IsNullOrEmpty(searchString))
            {
                rooms = rooms.Where(r => r.Name.ToLowerInvariant().Contains(searchString.ToLowerInvariant()) ||
                                    r.Description.ToLowerInvariant().Contains(searchString.ToLowerInvariant()));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    rooms = rooms.OrderByDescending(s => s.Name);
                    break;
                case "Date":
                    rooms = rooms.OrderBy(s => s.AddedDate);
                    break;
                case "date_desc":
                    rooms = rooms.OrderByDescending(s => s.AddedDate);
                    break;
                default:
                    rooms = rooms.OrderBy(s => s.Name);
                    break;
            }

            int pageSize = 10;
            return View(await PaginatedList<Room>.CreateAsync(rooms.AsNoTracking(), page ?? 1, pageSize));
        }

        // GET: Room/Details/5
        public ActionResult Details(int id)
        {
            var room = _unitOfWork.RoomRepository.GetAll().Include(x => x.Place).FirstOrDefault(x => x.Id == id);

            return View(room.ToRoomDetailsDto());
        }


        // GET: Room/Create
        public ActionResult Create()
        {
            var roomCreateDto = new RoomDto();

            var places = _unitOfWork.PlaceRepository.GetAll().Include(p => p.Rooms).AsQueryable();

            if (places != null && places.Any())
            {
                roomCreateDto.Places = new List<PlaceDto>();

                foreach (var place in places)
                {
                    roomCreateDto.Places.Add(place.ToPlaceDto());
                }
            }

            return View(roomCreateDto);
        }

        // POST: Room/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                var room = new Room();
                room.Name = collection["Name"];
                room.Description = collection["Description"];
                room.Capacity = Convert.ToInt32(collection["Capacity"]);
                room.Color = collection["Color"];
                room.PlaceId = Convert.ToInt64(collection["PlaceId"]);
                room.AddedDate = DateTime.Now;
                room.ModifiedDate = DateTime.Now;
                room.IPAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString();

                _unitOfWork.RoomRepository.Insert(room);
                _unitOfWork.Save();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: Room/Edit/5
        public ActionResult Edit(int id)
        {
            var room = _unitOfWork.RoomRepository.GetAll().Include(x => x.Place).FirstOrDefault(x => x.Id == id);
            var places = _unitOfWork.PlaceRepository.GetAll();
            var roomDto = room.ToRoomDto();
            if (roomDto != null)
            {
                roomDto.Places = new List<PlaceDto>();

                if (places != null)
                {
                    foreach (var place in places)
                    {
                        roomDto.Places.Add(place.ToPlaceDto());
                    }
                }
            }
            

            return View(roomDto);
        }

        // POST: Room/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                var room = _unitOfWork.RoomRepository.Get(id);
                room.Name = collection["Name"];
                room.PlaceId = Convert.ToInt64(collection["PlaceId"]);
                room.Color = collection["Color"];
                room.ModifiedDate = DateTime.Now;
                room.IPAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString();

                _unitOfWork.RoomRepository.Update(room);
                _unitOfWork.Save();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Error");
            }
        }

        // POST: Room/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                var room = _unitOfWork.RoomRepository.Get(id);
                _unitOfWork.RoomRepository.Delete(room);
                _unitOfWork.Save();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Error");
            }
        }
    }
}

MRBooker/Views/Room/Create.cshtml
@model RoomDto

@{
    ViewData["Title"] = "Create room";
}

@Html.AntiForgeryToken()

<h2>Create room</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        @if (Model.Places == null || (Model.Places != null && !Model.Places.Any()))
        {
            <a asp-action="Create" asp-controller="Place">Create a Place first !</a>
        }
        else
        {
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Capacity" class="control-label"></label>
                    <input asp-for="Capacity" class="form-control" />
                    <span asp-validation-for="Capacity" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Color" class="control-label"></label>
                    <div id="color" class="input-group colorpicker-component">
                        <input asp-for="Color" class="form-control" value="#00aabb" />
                        <span asp-validation-for="Color" class="input-group-addon"></span>
                    </div>
                    <span asp-validation-for="Color" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PlaceId" class="control-label">Place (<a asp-action="Index" asp-controller="Place">view list</a>)</label>
                    <select asp-for="PlaceId" class="form-control"
                            asp-items="@(new SelectList(Model.Places, "Id", "Country"))">
                        <option>Please select one</option>
                    </select>
                    <span asp-validation-for="PlaceId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-secondary" />
                </div>
            </form>
        }
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script type="text/javascript">
        $(function () {
            $('#color').colorpicker();
        });
    </script>
}

MRBooker/Views/Room/Details.cshtml
@model RoomDetailsDto
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Room details</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Capacity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PlaceDetails)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlaceDetails)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AddedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AddedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IpAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IpAddress)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

MRBooker/Views/Room/Edit.cshtml
@model RoomDto

@{
    ViewData["Title"] = "View";
}

@Html.AntiForgeryToken()

<h4>Room: @Model.Name</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <div id="color" class="input-group colorpicker-component">
                    <input asp-for="Color" class="form-control" value="@Model.Color" />
                    <span asp-validation-for="Color" class="input-group-addon"></span>
                </div>
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaceId" class="control-label">Place (<a asp-action="Index" asp-controller="Place">view list</a>)</label>
                <select asp-for="PlaceId" class="form-control"
                        asp-items="@(new SelectList(Model.Places, "Id", "Country"))">
                    <option>Please select one</option>
                </select>
                <span asp-validation-for="PlaceId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-secondary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script type="text/javascript">
        $(function () {
            $('#color').colorpicker();
        });
    </script>
}

MRBooker/Views/Room/Index.cshtml
@using MRBooker.Data.Models.Entities;
@using MRBooker.Wrappers;

@model PaginatedList<Room>

@{
    ViewData["Title"] = "Available rooms";
}

@Html.AntiForgeryToken()

<div class="container">
    <h3>Available rooms</h3>
    <p>
        <a asp-action="Create" class="btn btn-info">Create New</a>
    </p>
    <form asp-action="Index" method="get">
        <div class="form-actions no-color">
            <p>
                Search: <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
                <input type="submit" value="Search" class="btn btn-success" /> |
                <a asp-action="Index">Back to Full List</a>
            </p>
        </div>
    </form>
    @if (Model.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        <a asp-controller="Room" asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]">@Html.DisplayNameFor(model => model.First().Name)</a>
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.First().Description)
                    </th>
                    <th>
                        <a asp-controller="Room" asp-action="Index" asp-route-sortOrder="@ViewData["DateSortParm"]">@Html.DisplayNameFor(model => model.First().AddedDate)</a>
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.AddedDate)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <div class="delete-section" style="display: inline;">
                                <a class="delete-link" href="@Url.Action("Delete", new { id = item.Id })">Delete</a>
                                <div class="btn btn-danger btn-primary delete-confirm" style="display:none; padding: 1px 2px;" data-delete-id="@item.Id">Confirm Delete</div>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";

        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-page="@(Model.PageIndex - 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-default @prevDisabled">
            Prev
        </a>
        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-page="@(Model.PageIndex + 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-default @nextDisabled">
            Next
        </a>
    }
    else
    {
        <h2 class="text-danger">No Rooms available</h2>
    }
</div>

@section Scripts {
    @await Html.PartialAsync("_deleteScriptPartial");
}